#34 Linting
sosia-dev/sosia pull request #35
Opened 2024-08-19 15:11 UTC by nils-herrmann

The following changes were made:
- Doctoring for files and functions (with exception of tests)
- Imports at top of files (with exception of importing `Scientist` class)
- Explicit exceptions
- Removal of unnecessary parenthesis

2024-08-19 15:13 UTC, nils-herrmann commented on sosia/classes/original.py
> +        return self._search_group
Simplification by assigning `None` to self._search_group as default (see below)

2024-08-19 15:14 UTC, nils-herrmann commented on sosia/classes/original.py
> +        return self._matches
Simplification by assigning `None` to self._matches as default (see below)

2024-08-19 15:16 UTC, nils-herrmann commented on sosia/processing/querying.py
> +    except (AttributeError, TypeError, ValueError):
Should catch all the possible exceptions:
- AttributeError: `p.subtype` or `p.coverDate` might not exist.
- TypeError: `res` might not be a list or iterable, or `coverDate` might not be a string.
- ValueError: `int(p.coverDate[:4])` might fail if `coverDate[:4]`is not a valid integer string.

2024-08-20 11:44 UTC, Michael-E-Rose commented on sosia/processing/filtering.py
> +from pandas import DataFrame
There needs to be a newline here

2024-08-20 11:46 UTC, Michael-E-Rose commented on sosia/processing/finding.py
> +Module with functions for finding matches within a search group based on various criteria
Docstring should start on first line.

2024-08-20 11:50 UTC, Michael-E-Rose requested changes
Let docstrings always start on first line, and separate python base packages from third party packages.

2024-08-20 11:50 UTC, Michael-E-Rose commented on sosia/establishing/fields_sources.py
> +"""
Docstring should start on first line.

2024-08-20 11:50 UTC, Michael-E-Rose commented on sosia/establishing/__init__.py
> +"""
Docstring should start on first line.

2024-08-20 11:50 UTC, Michael-E-Rose commented on sosia/classes/__init__.py
> +"""
Docstring should start on first line.

2024-08-20 11:50 UTC, Michael-E-Rose commented on sosia/processing/finding.py
> +"""
Docstring should start on first line.

2024-08-20 11:50 UTC, Michael-E-Rose commented on sosia/processing/filtering.py
> +"""
Docstring should start on first line.

2024-08-20 14:15 UTC, Michael-E-Rose approved these changes

2024-08-20 14:16 UTC, merged